Traceback (most recent call last):
  File "infer.py", line 125, in <module>
    show_ground_truth(d, nusc_metadata, count)
  File "infer.py", line 42, in show_ground_truth
    vis = v.draw_dataset_dict(dict)
  File "/home/pmallya/anaconda3/envs/det2/lib/python3.6/site-packages/detectron2/utils/visualizer.py", line 494, in draw_dataset_dict
    labels = [names[i] for i in labels]
  File "/home/pmallya/anaconda3/envs/det2/lib/python3.6/site-packages/detectron2/utils/visualizer.py", line 494, in <listcomp>
    labels = [names[i] for i in labels]
IndexError: list index out of range
